Add download script again
UBC-MDS/Collision_Prediction pull request #10
Opened 2021-11-20 18:02 UTC by SiqiTao

2021-11-20 20:12 UTC, iamMoid approved these changes
Script looks good

2021-11-20 23:46 UTC, danfke commented
There is a discrepancy in the usage and options. Usage refers to file path, while options refers to out file.

2021-11-20 23:48 UTC, danfke commented on download_script.py
> +--out_file=<out_file>   Path (including filename) of where to store the csv file locally
Discrepancy between usage and options. Usage refers to filepath while options refers to out_file.

2021-11-20 23:52 UTC, iamMoid commented on download_script.py
> +    main(opt["--url"], opt["--filepath"])
Since the options have arguments "--url" and "--out_file", the second argument needs to be updated accordingly.

2021-11-20 23:53 UTC, iamMoid commented on download_script.py
> +        data.to_csv(out_file, index=False)
The first argument here should be "filepath" as you are mapping "out_file" to "filepath" as per the function parameters.

2021-11-20 23:54 UTC, danfke commented on download_script.py
> +        data.to_csv(out_file, index=False)
References out_file, which is not defined. Script likely doesn't work because of this.

2021-11-20 23:56 UTC, danfke requested changes
Script doesn't work. Need to delete references to out_file and replace it with filepath.

2021-11-21 00:05 UTC, danfke approved these changes
Script seems to work fine now.

2021-11-21 00:06 UTC, merged